In [1]:
import numpy as np
import tensorflow as tf
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)



/Users/lai/miniconda3/envs/lai-env/lib/python3.13/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(


In [2]:
X_train = np.array([1.0, 2.0]).reshape(-1, 1)
Y_train = np.array([300.0, 500.0]).reshape(-1, 1)
print(X_train)
print(Y_train)

[[1.]
 [2.]]
[[300.]
 [500.]]


In [3]:
linear_layer = tf.keras.layers.Dense(units=1, activation='linear')

In [4]:
linear_layer.get_weights()

[]

In [5]:
a1 = linear_layer(X_train[0].reshape(1, 1))
w, b = linear_layer.get_weights()
print(w, b)

[[-1.5626389]] [0.]


In [6]:
set_w = np.array([[200]])
set_b = np.array([100])

linear_layer.set_weights([set_w, set_b])
print(linear_layer.get_weights())

[array([[200.]], dtype=float32), array([100.], dtype=float32)]


In [7]:
a1 = linear_layer(X_train[0].reshape(-1, 1))
print(a1)
alin = X_train[0].reshape(-1, 1) @ set_w + set_b
print(alin)

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)
[[300.]]


In [8]:
pred_tf = linear_layer(tf.constant(X_train))
pred_np = X_train @ set_w + set_b

print(pred_tf)
print(pred_np)

tf.Tensor(
[[300.]
 [500.]], shape=(2, 1), dtype=float32)
[[300.]
 [500.]]


In [9]:
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

In [ ]:
model = tf.keras.Sequential([
    tf.keras.Input(shape=(1,)),
    tf.keras.layers.Dense(1, activation='sigmoid', name='L1')
])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ L1 (Dense)                      │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
logistic_layer = model.get_layer('L1')


In [12]:
w, b = logistic_layer.get_weights()
print(w, b)
print(w.shape, b.shape)

[[-0.99361634]] [0.]
(1, 1) (1,)


In [13]:
set_w = np.array([[2]])
set_b = np.array([-4.5])
logistic_layer.set_weights([set_w, set_b])
print(logistic_layer.get_weights())

[array([[2.]], dtype=float32), array([-4.5], dtype=float32)]


In [14]:
def signmoid(e):
    return 1 / (1 + np.exp(-e))

In [15]:
a1 = model.predict(X_train[0].reshape(-1, 1))
alog = signmoid(set_w @ X_train[0].reshape(-1, 1) + set_b)
print(a1, alog)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
[[0.01098694]] [[0.01098694]]
